export default {
  environment: process.env.NS_NODE_ENV || 'dev',
  baseUrl: process.env.NS_API_PATH || '/notification-service',
  session: process.env.NS_SESSION || 'secret-boilerplate-token',
  token: process.env.NS_TOKEN || 'secret-jwt-token',
  database: {
    name: process.env.NS_DB_NAME || 'notificationdb',
    user: process.env.NS_DB_USER || 'arjit',
    password: process.env.NS_DB_PASSWORD || 'arjit',
    host: process.env.NS_DB_HOST || 'localhost',
    port: process.env.NS_DB_PORT || '5432',
    dialect: process.env.NS_DB_DIALECT || 'postgres',
  },
  LIMIT: process.env.NS_LIMIT || 10,
  OFFSET: process.env.NS_OFFSET || 0,
  PORT: process.env.NS_PORT || 4006,
  APP_NAME: process.env.NS_APP_NAME || 'notification',
  BACKEND_URL: process.env.NS_BACKEND_URL || 'http://localhost:4006',
  AWS_SSM_KEY: process.env.NS_AWS_SSM_KEY,
  AWS_ACCESS_KEY_ID: process.env.NS_AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.NS_AWS_SECRET_ACCESS_KEY,
  AWS_REGION: process.env.NS_AWS_REGION || 'ap-south-1',
  AWS_SQS_QUEUE_URL_EMAIL: process.env.NS_AWS_SQS_QUEUE_URL_EMAIL,
  AWS_SQS_MESSAGE_GROUP_ID_EMAIL: process.env.NS_AWS_SQS_MESSAGE_GROUP_ID_EMAIL,
  AWS_SQS_QUEUE_URL_PUSH: process.env.NS_AWS_SQS_QUEUE_URL_PUSH,
  AWS_SQS_MESSAGE_GROUP_ID_PUSH: process.env.NS_AWS_SQS_MESSAGE_GROUP_ID_PUSH,
  FROM_EMAIL_ADDRESS: process.env.NS_FROM_EMAIL_ADDRESS,
  AWS_ACCESS_DENIED_EXCEPTION: 'AccessDeniedException',
  MAX_RETRY_IF_EMAIL_FAILED: 1,
  RETRY_EMAIL_DELAY: 30000, // In milliseconds
  MAX_NO_OF_MESSAGES_TO_RETRIVE_FROM_SQS: 10,
  AWS_SQS_WAIT_TIME_IN_SECONDS: 10,
  IGNORE_OLD_TOKENS_IN_DAYS: 30,
};
